server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 177000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
      connection:
        characterEncoding: utf8mb4
        useUnicode: true
        CharSet: utf8mb4


jwt:
  secret: ${JWT_SECRET}
  token:
    refresh-expiration-time: 6_000_000
    access-expiration-time: 6_000_000